[package]
name = "roadmap_sh_expense_tracker"
version = "0.1.0"
edition = "2024"
description = "A simple expense tracker CLI application"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[[bin]]
name = "expense-tracker"           # 👈 This is the CLI binary name
path = "src/main.rs"
